Repository WGBH-MLA/ov-deploy, pull requests merged in 2022-07, with the labels that each got.

#12 Adds command line script for deploying Open Vault resources
  .gitignore
  cli.py
  deploy
  deployer.py
  ov-nginx/Dockerfile
  ov-nginx/nginx.conf
Labels: enhancement :heavy_plus_sign:, CD :building_construction:

#15 Automatically create releases based on closed milestones
  .github/release.yml
  .github/workflows/draft-release.yml
Labels: enhancement :heavy_plus_sign:, CD :building_construction:

#16 Create sync-labels.json data to synchronize labels acros repos
  sync-labels.json
Labels: documentation :scroll:, maintenance :wrench:

#17 Sync milestone data with sync-milestones.json
  sync-milestones.json
Labels: documentation :scroll:, enhancement :heavy_plus_sign:, maintenance :wrench:

#18 Migrate to using upstream nginx image directly
  ov-nginx/Dockerfile
  ov-nginx/nginx.conf
Labels: CD :building_construction:, maintenance :wrench:

#21 Jumpbox :toolbox:
  jumpbox/Dockerfile
Labels: enhancement :heavy_plus_sign:, CD :building_construction:, maintenance :wrench:

#20 Draft release: with WGBH-MLA/milestones
  .github/workflows/draft-release.yml
  sync-milestones.json
Labels: CD :building_construction:, maintenance :wrench:

#22 deploy refactor
  cli.py
  deployer.py
Labels: documentation :scroll:, CD :building_construction:, maintenance :wrench:

#26 Adds jumpbox to deployer
  cli.py
  deployer.py
Labels: enhancement :heavy_plus_sign:, CD :building_construction:

#28 Issue templates :memo:
  .github/ISSUE_TEMPLATE/Because-Done.yml
  .github/ISSUE_TEMPLATE/Bug-Report.yml
Labels: maintenance :wrench:
